apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`steponedockerregistry.co.in`) && PathPrefix(`/api`)
      services:
        - name: backend
          port: 80
