apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend-ingressroute
  namespace: dev
spec:
  entryPoints:
    - web 
  routes:
    - kind: Rule
      match: Host(`api-dev.steponedockerregistry.co.in`)
      services:
        - name: backend
          port: 80
  tls:
    secretName: wildcard-cert
