apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend-ingressroute
  namespace: dev
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`dev.steponedockerregistry.co.in`) && PathPrefix(`/api`)
    services:
    - name: backend
      port: 80
