apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pythonicrahul/basic-notes-app-backend:dev1
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: config-map-dev1
                  key: DATABASE_URL
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      restartPolicy: Always
