apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingressroute
  namespace: main
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`heyrahul.cloud`)
      services:
        - name: frontend
          port: 80
