apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pythonicrahul/basic-notes-app-frontend:main
        env:
        - name: REACT_APP_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: config-map-main
              key: REACT_APP_API_BASE_URL
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      restartPolicy: Always
