apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingressroute
  namespace: dev
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`app-dev.heyrahul.cloud`)
      services:
        - name: frontend
          port: 80