name: Dynamic Environment Setup

on:
  push:
    branches:
      - 'dev*'

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    env:
      GITHUB_HEAD_REF: ${{ github.head_ref }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Execute Python script
        run: python create_env.py

      - name: Commit and Push Changes
        run: |
          # Set the user name and email to avoid conflicts
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Add, commit, and push the changes
          git add .
          git commit -m "Auto-commit: Update environment files for ${{ github.ref }}"
          git push
