name: Dynamic Environment Setup

on:
  push:
    branches:
      - 'dev*'

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install GitHub CLI (gh)
        run: |
          # Replace with the latest version if needed
          GH_VERSION="1.16.0"
          curl -sSL "https://github.com/cli/cli/releases/download/v${GH_VERSION}/gh_${GH_VERSION}_linux_amd64.tar.gz" -O

          # Extract the binary
          sudo tar -xvf gh_${GH_VERSION}_linux_amd64.tar.gz -C /usr/local/bin/

          # Verify that the installation was successful
          gh --version

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Execute Python script
        run: python create_env.py

      - name: Commit and Push Changes
        run: |
          # Set the user name and email to avoid conflicts
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Add, commit, and push the changes
          git add .
          git commit -m "Auto-commit: Update environment files for ${{ github.ref }}"
          git push
