name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.CONTAINER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push backend Docker image
      working-directory: backend
      run: |
        docker build -t ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/basic-notes-app-backend:latest .
        docker push ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/basic-notes-app-backend:latest

    - name: Build and push frontend Docker image
      working-directory: frontend
      run: |
        docker build -t ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/basic-notes-app-frontend:latest .
        docker push ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/basic-notes-app-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up kubectl
      run: echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: | 
        kubectl apply -f k8s/main/backend
        kubectl apply -f k8s/main/frontend
      env:
        KUBECONFIG: ./kubeconfig.yaml

    - name: Trigger Rolling Restart of Backend Deployment
      run: kubectl rollout restart deployment backend
      env:
        KUBECONFIG: ./kubeconfig.yaml

    - name: Trigger Rolling Restart of Frontend Deployment
      run: kubectl rollout restart deployment frontend
      env:
        KUBECONFIG: ./kubeconfig.yaml

    - name: Clean up
      run: rm kubeconfig.yaml
