name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.CONTAINER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push backend Docker image
      working-directory: backend
      run: |
        docker build -t ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/mysql-backup:latest .
        docker push ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/mysql-backup:latest

    - name: Build and push frontend Docker image
      working-directory: frontend
      run: |
        docker build -t ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/mysql-backup:latest .
        docker push ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/mysql-backup:latest
